.PHONY: run all clean force help

help:
	@echo "In order to build the software, some make variables have to be"
	@echo "defined.  Properties like the dimension of the polycubes can be"
	@echo "adjusted but must be known at compile time.  To that end, you"
	@echo "can specify variables as parameters, like in:"
	@echo ""
	@echo "    make run DIM=3 CELLS=10 ..."
	@echo ""
	@echo "Known variables are:"
	@echo "DIM             Mandatory.  The dimension of the polycubes."
	@echo "                Supported are dimensions from 2 to 15."
	@echo "CELLS           The maximum number of cells in a polycube."
	@echo "                Mandatory when CUBES_VECT is not set (default)."
	@echo "CUBES_VECT      Use a std::vector as container for the poly-"
	@echo "                cubes. The default uses a std::array which is"
	@echo "                more efficient but requires to specify CELLS."
	@echo "ENDIAN_AGNOSTIC Don't use code that makes explicit use of the"
	@echo "                host's endianess.  The code will be more generic"
	@echo "                but slower.  Default is off."
	@echo "SORT_THRESHOLD  For polycubes with this number of cells or less,"
	@echo "                sort cells by re-building the polycube.  For"
	@echo "                polycubes with more cells use std::sort."
	@echo "                Default is 14."
	@echo "MAX_DIAGONAL_LENGTH  The maximal length of polycubes' diagonals."
	@echo "                Default is CELLS when defined, 80 otherwise."
	@echo "DEBUG           Assertions won't be void. Off per default."
	@exit 0

SHELL = /bin/bash
MODULES := main diagnostic have cubes cubes-border

###########################################################################
# http://make.mad-scientist.net/papers/advanced-auto-dependency-generation/

SRCS := $(MODULES:%=%.cpp)
OBJS := $(SRCS:%.cpp=%.obj)

DEPDIR := .deps
DEPFLAGS = -MT $@ -MMD -MP -MF $(DEPDIR)/$*.d

$(DEPDIR): ; @mkdir -p $@

DEPFILES := $(SRCS:%.cpp=$(DEPDIR)/%.d)
$(DEPFILES):

include $(wildcard $(DEPFILES))
###############################################################################

GXX = g++-14

EXTRA_DEP = config-dim.h config-debug.h config-endian.h Makefile

# Several PRs exist like PR124207 for wrong bounds warnings.
WARN  = -W -Wall -Wno-stringop-overflow -fmax-errors=1
DEB = -g0

HOST_FLAGS += $(WARN) -O3 $(DEB) -fopenmp $(FLAGS)

HOST_CXXFLAGS = -std=c++17 -fno-exceptions $(HOST_FLAGS) $(CXXFLAGS)

def_if = @if [ -n "$($(1))" -a "$($(1))" != "0" ]; \
	 then echo "\#define $(1)" >> $2; \
	 fi

def_val = @if [ -n "$($(1))" ]; \
	  then echo "\#define $(1) $($(1))" >> $2; \
	  fi

config-debug.h: force
	@echo "// $@: Auto-generated by Makefile." > $@.in
	$(call def_if,DEBUG,$@.in)
	./move-if-change $@.in $@
	@cat $@

config-dim.h: force
	@if [ -z $(DIM) ]; then \
		echo "error: DIM must be defined, see 'make help'."; \
		exit 1; \
	fi
	@echo "// $@: Auto-generated by Makefile." > $@.in
	$(call def_val,DIM,$@.in)
	$(call def_val,CELLS,$@.in)
	$(call def_if,CUBES_VECT,$@.in)
	$(call def_val,MAX_DIAGONAL_LENGTH,$@.in)
	$(call def_val,SORT_THRESHOLD,$@.in)
	./move-if-change $@.in $@
	@cat $@

config-endian.h: force
	@echo "// $@: Auto-generated by Makefile." > $@.in
	$(call def_if,ENDIAN_AGNOSTIC,$@.in)
	./move-if-change $@.in $@
	@cat $@

%.obj: %.cpp
%.obj: %.cpp $(EXTRA_DEP) $(DEPDIR)/%.d | $(DEPDIR)
	$(GXX) -c $< $(HOST_CXXFLAGS) -o $@ $(I_GMP) $(DEPFLAGS)

all: dorun

dorun: $(OBJS) $(EXTRA_DEP)
	$(GXX) $(HOST_CXXFLAGS) $(OBJS) -o $@ -Wl,--gc-sections -lm

NICE ?= 20

run: dorun
	time nice -$(NICE) ./$< $(ARGS)
#	convert out-1.ppm out-1.png
#	convert out-2.ppm out-2.png

.PHONY: progress rotor alloc

progress:
	g++ test-progress.cpp -o prog.x -Wall -O3 -fopenmp $(FLAGS)
	./prog.x

rotor:
	g++ test-rotation.cpp -o rotor.x -Wall -O3 -fopenmp $(FLAGS)
	./rotor.x

canon:
	$(GXX) test-canonical.cpp -o canon.x -Wall -O3 -fopenmp $(FLAGS)
	./canon.x

ALLOC_CPP = test-allocator.cpp diagnostic.cpp
alloc:
	$(GXX) $(ALLOC_CPP)  -o alloc.x -Wall -O3 -fopenmp $(FLAGS)
	./alloc.x

clean:
	rm -f -- $(wildcard *.[iso] *.ii *.obj *.exe *.x *.x.* dorun)
	rm -f -- $(wildcard *.lst *.lss *.out *.map *ltrans* *.res *.wpa.*)
	rm -f -- $(wildcard config-*.h config-*.h.in)
	rm -rf -- $(wildcard .deps)

demo.x: demo.cpp Makefile
	g++ -Wall -O3 -g2 -std=c++11 $< -o $@ -fopenmp

xxx: demo.x
	time ./demo.x $(ARGS)
